modLoader = "javafml"
loaderVersion = "[4,)"
license = "All Rights Reserved"

[[mods]]
modId = "celestial_nail"
version = "${version}"
displayName = "Celestial Nail"
authors = "NsTut"
description = "An administrator-controlled divine strike: summon a persistent Celestial Nail in the sky, then launch it straight down to carve a staged high-power impact crater."

[[dependencies.celestial_nail]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.celestial_nail]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config="celestial_nail.client.mixins.json"
