modLoader = "javafml"
loaderVersion = "[47,)"
license = "All Rights Reserved"

[[mods]]
modId = "celestial_nail"
version = "${version}"
displayName = "Celestial Nail"
authors = "NsTut"
description = "An administrator-controlled divine strike: summon a persistent Celestial Nail in the sky, then launch it straight down to carve a staged high-power impact crater."

[[dependencies.celestial_nail]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.celestial_nail]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.celestial_nail]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.celestial_nail]]
modId = "perfomant_boom"
mandatory = true
versionRange = "[1.1.0,2.0.0)"
ordering = "AFTER"
side = "BOTH"
